# Generated by Django 5.1.4 on 2025-02-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_bloodrequestmodel_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="collected_blood",
            field=models.JSONField(default=dict),
        ),
    ]
