# Generated by Django 5.1.4 on 2024-12-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="DOB",
            field=models.DateField(blank=True, null=True),
        ),
    ]
