# Generated by Django 5.1.4 on 2024-12-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_bloodrequestmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=10,
            ),
        ),
    ]
