# Generated by Django 5.1.4 on 2024-12-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_user_blood_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("user", "User"), ("organization", "Organization")],
                default="user",
                max_length=20,
            ),
        ),
    ]
