# Generated by Django 5.1.4 on 2024-12-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_event_userevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendee_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
