# Generated by Django 5.1.4 on 2025-01-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_event_attendee_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(),
        ),
    ]
