# Generated by Django 5.1.4 on 2025-01-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_event_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inventory", models.JSONField(default=dict)),
                (
                    "organization",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "organization"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
