# Generated by Django 5.1.4 on 2025-01-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_bloodinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="",
                max_length=10,
            ),
        ),
    ]
