# Generated by Django 5.1.4 on 2025-01-03 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "morning"),
                            ("day", "day"),
                            ("evening", "evening"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "organization"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizatio_name",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
