# Generated by Django 5.1.4 on 2025-01-03 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_bookings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "user"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
