# Generated by Django 5.1.4 on 2025-01-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_bookings_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="user_blood_group",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="bookings",
            name="user_phone_number",
            field=models.CharField(default="", max_length=20),
        ),
    ]
