# Generated by Django 5.1.4 on 2025-01-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_bookings_user_blood_group_bookings_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="user_file/"),
        ),
    ]
