# Generated by Django 5.1.4 on 2025-01-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_user_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="shift",
            field=models.CharField(
                choices=[
                    ("morning", "morning"),
                    ("afternoon", "afternoon"),
                    ("evening", "evening"),
                ],
                max_length=10,
            ),
        ),
    ]
