# Generated by Django 5.1.4 on 2025-01-05 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_alter_bookings_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="collabrator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"user_type": "organization"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collabrator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
