# Generated by Django 5.1.4 on 2025-01-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_event_collabrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="local_address",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="org_type",
            field=models.CharField(default="", max_length=10, null=True),
        ),
    ]
