# Generated by Django 5.1.4 on 2025-01-24 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_user_city_user_local_address_user_org_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
