# Generated by Django 5.1.4 on 2025-01-24 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_event_end_time_event_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="start_date",
            new_name="start_time",
        ),
    ]
