# Generated by Django 5.1.4 on 2025-01-24 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_rename_start_date_event_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkBloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateField(auto_now_add=True)),
                ("location", models.CharField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "organization"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_blood_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodGroupRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "bulk_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_group_requirements",
                        to="app.bulkbloodrequest",
                    ),
                ),
            ],
        ),
    ]
