# Generated by Django 5.1.4 on 2025-01-25 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_bulkbloodrequest_bloodgrouprequirement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulkbloodrequest",
            name="organization",
        ),
        migrations.DeleteModel(
            name="BloodGroupRequirement",
        ),
        migrations.DeleteModel(
            name="BulkBloodRequest",
        ),
    ]
