# Generated by Django 5.1.4 on 2025-01-25 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_remove_bulkbloodrequest_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkRequestmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_request", models.JSONField(default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "organization"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_blood_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
