# Generated by Django 5.1.4 on 2025-01-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_bulkrequestmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
