# Generated by Django 5.1.4 on 2025-01-25 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkrequestmodel",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
