# Generated by Django 5.1.4 on 2025-02-07 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_bulkrequestmodel_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="attendee_count",
            new_name="donor_attendee_count",
        ),
    ]
