# Generated by Django 5.1.4 on 2025-02-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_rename_attendee_count_event_donor_attendee_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="expected_donor_count",
            field=models.IntegerField(default=0),
        ),
    ]
