# Generated by Django 5.1.4 on 2025-02-08 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_event_expected_donor_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDonationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donation_count", models.PositiveIntegerField(default=0)),
                ("last_donated_date", models.DateField(blank=True, null=True)),
                (
                    "last_donation_event_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
