# Generated by Django 5.1.4 on 2025-02-08 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_userdonationinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDonationInfo",
        ),
    ]
