# Generated by Django 5.1.4 on 2025-02-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_event_volunteer_attendee_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequestmodel",
            name="location",
        ),
        migrations.AddField(
            model_name="bloodrequestmodel",
            name="district",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="bloodrequestmodel",
            name="province",
            field=models.CharField(default="", max_length=30),
        ),
    ]
